In [1]:
import sys
dll_path = r'/home/photon/Documents/09_ROS/some_cybernetic_scheisse/dobot_lib'
sys.path.insert(1,dll_path)
import DobotDllType as dType
from math import pi
import numpy as np
import time
import scipy.optimize as optimize
from math import dist, atan2
from itertools import combinations, islice
import pickle
import ipywidgets as widgets
from typing import Optional

# api = dType.load(dll_path)

In [26]:
def coords_from_chess_pos(pos):
    # from chess pos (e.g. 'e4') into local chess coords
    # letters - xi axis, numbers - eta. Origin at center of a1
    if isinstance(pos, str):
        char, num = pos.lower()
        xi = ord(char) - ord('a')
        eta = int(num) - 1
        return np.array([xi, eta], dtype=float)
    if isinstance(pos, np.ndarray) and pos.dtype == float:
        return pos
    
    return np.array(list(map(coords_from_chess_pos, pos)))
    

def find_intersections(o1, r1, o2, r2, eps=.1):
    # finds intersection points of 2 circles
    # if no intersection, raises exception
    # o1 and o2 have to be passed counterclockwise
    o1, o2 = numpify(o1, o2)
    d = dist(o1, o2)
    assert d <= r1+r2
    assert d > eps
    a = (r1**2-r2**2+d**2)/(2*d)
    h = (r1**2 - a**2)**.5
    P = (o2-o1)*a/d+o1
    perp_ = perp(o2-o1)
    I1, I2 = P+h*perp_, P-h*perp_
    if is_clockwise(o1 - I1, o2 - I1):
        return I1
    return I2

def normalize(vec):
    return np.array(vec)/length(vec)

def perp(vec):
    return normalize(vec)[::-1]*np.array([-1,1])

def length(vec):
    return np.linalg.norm(vec, axis=-1, keepdims=True)

def numpify(*args):
    arrays = [0]*len(args)
    for i, arg in enumerate(args):
        arrays[i] = arg.astype(np.float32) if isinstance(arg, np.ndarray) else np.array(arg, dtype=np.float32)
    return arrays

def find_angle(vec_a, vec_b):
    """
    finds angle from vec_b to vec_a in [0; 2pi) (counterclockwise)
    """
    return (np.arctan2(*vec_a.reshape(-1, 2).T) - np.arctan2(*vec_b.reshape(-1, 2).T))%(2*pi)

def count_coincides(A, points, eps = .1):
    return len([0 for point in points if dist(A, point) < eps])

def is_clockwise(vec1, vec2):
    # finds if vec2 is rotated clockwise from vec1
    cross = vec1[0]*vec2[1] - vec1[1]*vec2[0]
    assert cross != 0
    return cross < 0

def find_origin(board_coords, dobot_coords, tile_size):
    # find center, given coords of 3 points
    # points all have different angle for 1st joint
    samples = len(board_coords)
    board_coords = coords_from_chess_pos(board_coords)
    dobot_coords = np.array(dobot_coords)
    dists = np.linalg.norm(dobot_coords, axis=1) / tile_size
    
    candidates = []
    for i, j in combinations(np.arange(samples), 2):
        if np.arctan2(*dobot_coords[i]) > np.arctan2(*dobot_coords[j]):
            i, j = j, i
        candidates.append(find_intersections(board_coords[i], dists[i], board_coords[j], dists[j]))
#     candidates = np.array(candidates)
    
#     barycenters = []
#     for centers in combinations(candidates, samples):
#         baric = np.mean(centers, axis=0)
#         max_dist = cdist(baric[None, :], centers).max().max()
#         barycenters.append((baric, max_dist))
#     best_baryc = min(barycenters, key=lambda tup: tup[-1])
    return candidates, cdist(dobot_coords, dobot_coords) / cdist(board_coords, board_coords)

def find_rot_angle(p_b, q_a, origin):
    """
    returns rotation matrix R_ab
    p_b - coordinates of point in board frame
    q_a - coordinates shown by dobot
    origin - coordinates of dobot's origin in board frame
    """
    p_b = coords_from_chess_pos(p_b)
    p_b, q_a, origin = numpify(p_b, q_a, origin)
    # same vector in different frames
    v_b = normalize(p_b-origin)
    v_a = normalize(q_a)
    
    angle = find_angle(v_b, v_a)
    return angle

def find_l(board_coords, dobot_coords, origin):
    """
    board_coords - coords of 3 points in board's frame
    dobot_coords - coords shown by dobot
    origin - origin of dobot in board's frame
    
    returns d - offset, l - size of tile (both in mm, if given dobot coords are in mm)
    """
    board_coords = list(map(coords_from_chess_pos, board_coords))
    dobot_coords, origin = numpify(dobot_coords, origin)
    lengths_b = [length(point-origin) for point in board_coords]
    lengths_a = [length(point) for point in dobot_coords]
    def la_from_lb(l_b, l):
        return l*l_b
    popt, _ = optimize.curve_fit(la_from_lb, lengths_b, lengths_a, [28])
    print('d, l optimization error:', sum([abs(la_from_lb(l_b, *popt) - l_a) for l_b, l_a in zip(lengths_b, lengths_a)]))
    return popt

def rot_matr(phi):
    c, s = np.cos(phi), np.sin(phi)
    return np.array([[c, -s],
                     [s, c]])

0.3453841273212816

In [ ]:

np.linalg.norm(t - , axis=1)

/tmp/ipykernel_5235/1253679595.py:33: RuntimeWarning: invalid value encountered in divide
  return np.array(vec)/length(vec)


array([       nan, 0.52580225, 0.8331401 , 0.9705671 , 0.5468927 ],
      dtype=float32)

array([4.7209105], dtype=float32)

In [17]:
t.mean()

[array([ 3.23030853, -6.28200401]),
 array([ 2.96178717, -6.41297797]),
 array([ 2.78345765, -6.4923671 ]),
 array([ 3.91432681, -6.64475509]),
 array([ 3.46801273, -6.41866103]),
 array([ 3.13034129, -6.46068359])]

In [35]:
for i in range(len(bc)):
    mask = np.arange(len(bc)) != i
    print(bc0[i], end='&')
    t, tt = find_origin(bc0[mask], dc[mask], 28.5)
    angles = []
    for bc_, dc_, t_ in zip(bc[mask], dc[mask], t):
        angles.append(find_rot_angle(bc_, dc_, t_))
    v3 = np.var(np.array(angles)*180/np.pi)**.5
    v1, v2 = np.var(np.linalg.norm(t - np.mean(t, axis=0), axis=1), axis=0) ** .5 * 28.5, np.var(tt[~np.isnan(tt)])**.5
    print(f"{v1:.1f}&{v3:.2f}\\\\\hline")

a1&12.9&2.60\\\hline
h1&15.6&0.73\\\hline
g5&14.1&1.36\\\hline
c5&7.3&2.24\\\hline
d3&5.6&2.04\\\hline


/tmp/ipykernel_5235/1832011248.py:83: RuntimeWarning: invalid value encountered in divide
  return candidates, cdist(dobot_coords, dobot_coords) / cdist(board_coords, board_coords)


In [39]:
s = "a1&12.9&3.22\\\hline h1&15.6&5.83\\\hline g5&14.1&4.26\\\hline c5&7.3&3.41\\\hline d3&5.6&1.42\\\hline".split("&")[1:]

In [43]:
from scipy.stats import pearsonr
pearsonr(dists[::2], dists[1::2])

PearsonRResult(statistic=0.8511947339928971, pvalue=0.06734757613166603)

In [42]:
dists = [float(t[:4]) for t in s]

In [177]:
def dobot_xy_from_board_xy(R_ab, origin, tile_size, board_xy):
    """
    board_xy - can either be like 'b3' or like [1, 2]
    """
    t = R_ab @ (coords_from_chess_pos(board_xy) - origin)
    return t * tile_size

In [229]:
# dc[4] += (dc[3] - dc[0] - (dc[1] - dc[0]) / 7 * 2) / 4
# bc[4] += np.array([0, 1])
# bc0[4] = 'd4'

In [316]:
t = []
for i in range(len(bc)):
    mask = np.arange(len(bc)) != i
    orig, _ = find_origin(bc0[mask], dc[mask], 29)
    rot_ang = find_rot_angle(bc0[mask], dc[mask], orig)
    print(dobot_xy_from_board_xy(rot_matr(rot_ang), orig, 29, bc0[i]), dc[i])
    t.append(np.linalg.norm(dobot_xy_from_board_xy(rot_matr(rot_ang), orig, 29, bc0[i]) - dc[i]))
print(t, np.mean(t))

[178.26376146  96.25752414] [178.24612427  93.58605194]
[ 184.73538763 -108.24751375] [ 180.59434509 -104.79747009]
[295.99515618 -76.65015109] [299.90182495 -75.02609253]
[294.65647003  40.10596004] [297.07235718  40.82880783]
[238.73923363   9.76936605] [237.14205933   9.75437546]
[2.6715304239755424, 5.3899011607659055, 4.230795090140595, 2.521709669288511, 1.597244652841996] 3.28223619940251


In [309]:
np.mean([4.311467851261223,
5.846664515519671,
3.116381527667872,
1.7523806293696742,
1.5463507036901614,
])

3.314649045501721

In [78]:
data = {'bc': ['h1', 'a1', 'd5'], 'dc': [[168.06251525878906, -108.178955078125, -63.15735626220703, -33.96176528930664], [167.61117553710938, 89.9608154296875, -63.85260009765625, 26.3892765045166], [285.451416015625, 7.739808559417725, -63.33761215209961, 0.045200467109680176]]}

In [281]:
data = {'bc': ['e8', 'g7', 'd4', 'h1'],
 'dc': [[266.4316101074219, -17.031978607177734],
  [212.35418701171875, 9.959300994873047],
  [295.51904296875, 88.67515563964844],
  [187.85848999023438, 170.5806427001953]],
 'j1': [-3.6577281951904297,
  2.6851744651794434,
  16.702701568603516,
  42.24030685424805]}

In [6]:
from scipy.spatial.distance import cdist
bc0 = np.array(data['bc'])

bc = np.array(list(map(coords_from_chess_pos, data['bc'])))
dc = np.array(data['dc'])[:, :2]
tile_size = np.nanmean(cdist(dc, dc) / cdist(bc, bc))

/tmp/ipykernel_5235/3358970743.py:6: RuntimeWarning: invalid value encountered in divide
  tile_size = np.nanmean(cdist(dc, dc) / cdist(bc, bc))


In [330]:
t = []
for i in range(len(bc)):
    mask = np.arange(len(bc)) != i
    optim = Optimizer().fit(bc[mask], dc[mask], 28.5)
    t.append(np.linalg.norm(optim.transform(bc[i]) - dc[i]))
print(t)
print(np.mean(t))

[3.223885094054794, 5.831016988781327, 4.256006259285622, 3.4131070706638083, 1.4199728417190027]
3.6287976509009106


In [9]:
for i in range(len(bc)):
    mask = np.arange(len(bc)) != i
    optim = Optimizer().fit(bc[mask], dc[mask], 28.5)
    t, tt = dc[i], optim.transform(bc[i])
    print(f"{bc0[i]}&({t[0]:.1f}, {t[1]:.1f})&({tt[0]:.1f}"
          f", {tt[1]:.1f})&{np.linalg.norm(t - tt):.2f}\\\\\\hline",end=" ")

a1&(178.2, 93.6)&(181.1, 95.2)&3.22\\\hline h1&(180.6, -104.8)&(186.2, -106.3)&5.83\\\hline g5&(299.9, -75.0)&(295.7, -74.7)&4.26\\\hline c5&(297.1, 40.8)&(294.0, 39.4)&3.41\\\hline d3&(237.1, 9.8)&(238.5, 10.0)&1.42\\\hline 

In [12]:
optim.twist[:2, :2] / 28.5

array([[ 0.0194836 ,  0.99981018],
       [-0.99981018,  0.0194836 ]])

In [75]:
from scipy.spatial.distance import cdist

In [3]:
data = {'bc': ['a1', 'h1', 'g5', 'c5', 'd3'], 'dc': [[178.24612426757812, 93.58605194091797, -63.57745361328125, 27.238235473632812], [180.59434509277344, -104.79747009277344, -63.09832763671875, -22.997629165649414], [299.9018249511719, -75.02609252929688, -62.68821716308594, -10.739964485168457], [297.0723571777344, 40.82880783081055, -63.51740264892578, 11.468629837036133], [237.14205932617188, 9.754375457763672, -62.855712890625, 11.468629837036133]]}

In [269]:
dc

array([[266.43161011, -17.03197861],
       [212.35418701,   9.95930099],
       [295.51904297,  88.67515564],
       [187.85848999, 170.5806427 ]])

In [268]:
bc

array([[4., 7.],
       [6., 6.],
       [3., 3.],
       [7., 0.]])

In [263]:
find_origin(bc0[mask], dc[mask], 26.84)

/tmp/ipykernel_13423/2464500959.py:23: RuntimeWarning: invalid value encountered in scalar power
  h = (r1**2 - a**2)**.5


(array([nan, nan]), nan)

In [283]:
for i in range(len(bc)):
    mask = np.arange(len(bc)) != i
    orig, _ = find_origin(bc0[mask], dc[mask], tile_size)
    rot_ang = find_rot_angle(bc0[mask], dc[mask], orig)
    new_rot_ang, new_orig = calibrate_by_optimizing(bc[mask], dc[mask], tile_size, [rot_ang, *orig])
    print(dobot_xy_from_board_xy(rot_matr(new_rot_ang), new_orig, tile_size, bc0[i]) - dc[i])


error distance is: 2.120939306796919
[-0.18917343 -1.22959818]
error distance is: 2.112312650212704
[ 1.0763129  -0.67043723]
error distance is: 1.6616842037952095
[-1.4409      1.07792939]
error distance is: 1.7216654431403835
[2.41022529 1.4128724 ]


In [254]:
def calibrate_by_optimizing(board_xy, dobot_xy, tile_size, defaults=None):
    def get_coords(x):
        phi, o_x, o_y = x
        summ = 0
        for p_b, p_a in zip(board_xy, dobot_xy):
            c, s = np.cos(phi), np.sin(phi)
            R_ab = np.array([[c, -s],
                             [s, c]])
            origin = np.array([o_x, o_y])
            t = R_ab@(coords_from_chess_pos(p_b) - origin)
            p_a_calc = t*tile_size
            summ += np.linalg.norm(p_a - p_a_calc)
        return summ
    if defaults is None:
        defaults = [0, 0, 0]
    optimizer = optimize.minimize(get_coords, defaults, method='Nelder-Mead', options={'maxiter':10**10})
    phi, o_x, o_y = optimizer.x
    print(f'error distance is: {get_coords(optimizer.x)}')
    return phi, np.array([o_x, o_y])

In [293]:
optim = Optimizer().fit(bc, dc, tile_size)
optim.transform(bc) - dc

array([[-0.07913821, -0.80234045],
       [ 0.65241558, -0.25939012],
       [-0.94330492,  0.52678203],
       [ 0.37002755,  0.53494854]])

In [294]:
optim.twist

array([[-2.68451937e+01, -3.44518110e-01,  3.76144874e+02],
       [ 3.44518110e-01, -2.68451937e+01,  1.68703964e+02],
       [ 0.00000000e+00,  0.00000000e+00,  1.00000000e+00]])

In [295]:
bc

array([[4., 7.],
       [6., 6.],
       [3., 3.],
       [7., 0.]])

In [8]:
class Optimizer:
    def __init__(self):
        self.twist = None
    
    @staticmethod
    def kabsch_umeyama(board_coords, dobot_coords, tile_size):
        assert dobot_coords.shape == board_coords.shape
        n, m = dobot_coords.shape

        E_dobot_coords = np.mean(dobot_coords, axis=0)
        E_board_coords = np.mean(board_coords, axis=0)
        # var_dobot_coords = np.var(dobot_coords, axis=0)
        var_dobot_coords = np.mean(np.linalg.norm(dobot_coords - E_dobot_coords, axis=1) ** 2)

        H = ((dobot_coords - E_dobot_coords).T @ (board_coords - E_board_coords)) / n
        U, D, VT = np.linalg.svd(H)
        d = np.sign(np.linalg.det(U) * np.linalg.det(VT))
        S = np.diag([1] * (m - 1) + [d])

        R = U @ S @ VT
        # scaling = np.diag(var_dobot_coords / np.trace(np.diag(D) @ S))
        # scaling = var_dobot_coords / np.trace(np.diag(D) @ S)
        scaling = tile_size
        offset = (E_dobot_coords - scaling * R @ E_board_coords)
        twist = np.vstack([
            np.hstack([scaling * R, offset.reshape(-1, 1)]),
            [0, 0, 1]
        ])
        return twist
    
    def fit(self, board_coords: np.ndarray, dobot_coords: np.ndarray, tile_size: float):
        self.twist = self.kabsch_umeyama(board_coords, dobot_coords, tile_size)
        return self
    
    def transform(self, board_coords: np.ndarray):
        only_one = board_coords.ndim == 1
        if only_one:
            board_coords = board_coords.reshape(1, -1)
        homog_board_coords = np.vstack([board_coords.T, np.ones(len(board_coords))])
        dobot_coords = (self.twist @ homog_board_coords).T[:, :2]
        if only_one:
            return dobot_coords[0]
        return dobot_coords
    
    @staticmethod
    def coords_from_chess_poses(pos):
        # from chess pos (e.g. 'e4') into local chess coords
        # letters - xi axis, numbers - eta. Origin at center of a1
        if isinstance(pos, str):
            char, num = pos.lower()
            xi = ord(char) - ord('a')
            eta = int(num) - 1
            return np.array([xi, eta], dtype=float)
        else:
            return np.array(list(map(coords_from_chess_pos, pos)))

In [272]:
class Pieces:
    def __init__(self, dobot):
        self.dobot = dobot
        
        # additional offset when carrying pieces
        self.default_offset = 20
        self.zero_height = None
        self.pieces_heights = {}
    
    def copy_from(self, other):
        self.zero_height = other.zero_height
        self.pieces_heights = other.pieces_heights
        return self
    
    def get_height(self, piece: str):
        # get piece's z coordinate by its name
        if piece is None:
            return self.zero_height + self.default_offset
        else:
            return self.pieces_heights[piece]
    
    def _dobot_height(self):
        return dType.GetPose(api)[2]
    
    def calibrate(self):
        # calibrate heights of pieces
        input('Move to zero height, then press Enter')
        self.zero_height = self.dobot.get_pos()[2]
        pieces = ['pawn', 'rook', 'knight', 'bishop', 'queen', 'king']
        for piece in pieces:
            input(f"Move to {piece}'s height, then press enter")
            self.pieces_heights[piece] = self.dobot.get_pos()[2]
            print(f'Height is {self.pieces_heights[piece]}')
        
    def trans_height(self):
        # height safe for transporting a piece
        return (max(self.pieces_heights.values()) - self.zero_height)*2 + self.default_offset + self.zero_height

In [188]:
class Board:
    def __init__(self, dobot):
        self.dobot = dobot
        self.R_ab = None
        self.origin = None
        self.tile_size = None
        self.offset = None
        self.coords_data = {'bc':[], 'dc':[]}
        self.optimizer = Optimizer()
    
    def read_coords(self, num_of_points=3, rewrite_coords=False):
        board_coords, dobot_coords = [], []
        if not rewrite_coords:
            board_coords, dobot_coords = self.coords_data['bc'], self.coords_data['dc']
        self.coords_data['bc'] = board_coords
        self.coords_data['dc'] = dobot_coords
        delta = widgets.RadioButtons(options=['0.1 mm', '1 mm', '10 mm'],)
        change_coords = [widgets.Button(description=descr) for descr in ['-X', '+X', '-Y', '+Y', '-Z', '+Z']]
        record = widgets.Button(description='record (leave field empty to stop recording)')
        inp = widgets.Text(description='coords on board (e.g. "a2")')
        def stop_recording():
            for button in change_coords + [record]:
                button.disabled = True
            print('stopped recording!')
            
        def on_click_record(b, temp={'num_of_points':num_of_points}):
            if inp.value == '':
                stop_recording()
            else:
                self.coords_data['bc'].append(inp.value)
                inp.value = ''
                self.coords_data['dc'].append(dType.GetPose(api)[:4])
                temp['num_of_points'] -= 1
                if not temp['num_of_points']:
                    stop_recording()
                    
        def change_coord_on_click(b):
            mask = {
                'X': [1, 0, 0],
                'Y': [0, 1, 0],
                'Z': [0, 0, 1]
            }[b.description[1]]
            mask = np.array(mask, dtype=float)
            mask *= -1 if b.description[0] == '-' else 1
            mask *= [.1, 1, 10][delta.get_state()['index']]
            self.dobot.move_to(*(self.dobot.get_xyz() + mask))
        
        record.on_click(on_click_record)
        for button in change_coords:
            button.on_click(change_coord_on_click)
        display(delta, *change_coords, record, inp)
    
    def optimize(self):
        self.optimizer.fit(
            np.array(Optimizer.coords_from_chess_poses(self.coords_data['bc'])),
            np.array(self.coords_data['dc'])[:, :2]
        )
        
    def coord_from_board(self, board_xy: np.ndarray):
        board_xy = np.array(board_xy, dtype=float)
        return self.optimizer.transform(board_xy)

In [248]:
class Dobot:
    def __init__(self, com, copy_from=None, from_data=None):
        self.com = com
        self.connect()
        self.pieces = Pieces(self)
        self.board = Board(self)
        if copy_from is not None:
            self.copy(copy_from)
        elif from_data is not None:
            self.copy_data(data)
    
    def connect(self):
        self.disconnect()
        print(dType.ConnectDobot(api, self.com, 115200))
        dType.SetQueuedCmdClear(api)
        dType.SetQueuedCmdStartExec(api)
        dType.SetHOMEParams(api, 200, 0, 200, 200, isQueued = 1)
        dType.SetPTPJointParams(api, 200, 200, 200, 200, 200, 200, 200, 200, isQueued = 1)
        dType.SetPTPCommonParams(api, 100, 100, isQueued = 1)
    
    def disconnect(self):
        dType.DisconnectDobot(api)
    
    def __del__(self):
        dType.DisconnectDobot(api)
    
    def reconnect(self):
        self.connect()
            
    def copy(self, other_dobot):
        try:
            self.calibrate_pos(0)
        except Exception as e:
            print('exception, while trying to calibrate')
        self.pieces = other_dobot.pieces
        
    def copy_data(self, data):
        self.pieces = data['pieces']
    
    def move_to(self, x=None, y=None, z=None, j4_rot=None, timeout=.5):
        x, y, z, j4_rot = [coord_orig if coord_orig is not None else coord_new 
                              for coord_orig, coord_new in zip((x, y, z, j4_rot), self.get_pos()[:4])]
        for _ in range(2):
            try:
                dType.SetPTPCmd(api,
                    dType.PTPMode.PTPMOVLXYZMode,
                    x, y, z, j4_rot,
                    isQueued = 1,
                    timeout = timeout
                )
            except RuntimeError as e:
                print(e)
                reconnect()
                time.sleep(.1)
            else:
                return
        raise e
    
    def move_to_tile(self, board_xy, chess_piece=None, height=None, j4_rot=None):
        dobot_xy = self.board.coord_from_board(board_xy)
        cur_pos = self.get_pos()
        if height is None:
            if chess_piece is None:
                height = cur_pos[2]
            else:
                height = self.pieces.get_height(chess_piece)
        if j4_rot is None:
            j4_rot = cur_pos[3]
        self.move_to(*dobot_xy, height, j4_rot)
    
    def get_xyz(self):
        return self.get_pos()[:3]
    
    def get_pos(self):
        return np.array(dType.GetPose(api))
    
    def move_piece(self, from_coords, to_coords, piece):
        trans_height = self.pieces.trans_height()
        self.move_to(z=trans_height)
        self.move_to_tile(from_coords, height=trans_height)
        self.move_to_tile(from_coords, height=self.pieces.get_height(piece))
        dType.SetEndEffectorSuctionCup(api, 1, 1, True)
        time.sleep(3)
        
        self.move_to_tile(from_coords, height=trans_height)
        self.move_to_tile(to_coords, height=trans_height)
        self.move_to_tile(to_coords, height=self.pieces.get_height(piece))
        dType.SetEndEffectorSuctionCup(api, 1, 0, True)
        time.sleep(1)

In [263]:
db.move_to_tile([4, 4])

In [195]:
db = Dobot('COM6')

[0, 2, 0, 'DobotSerial', '0.0.0', 25, 0, 0.0]


In [201]:
# with open('coords.txt', 'w') as f:
#     print(db.board.coords_data, file=f)
#     print(db.board.coords_data)

{'bc': ['h1', 'a1', 'd5'], 'dc': [[168.06251525878906, -108.178955078125, -63.15735626220703, -33.96176528930664], [167.61117553710938, 89.9608154296875, -63.85260009765625, 26.3892765045166], [285.451416015625, 7.739808559417725, -63.33761215209961, 0.045200467109680176]]}


In [ ]:
dType.ClearAllAlarmsState(api)

In [278]:
db.reconnect()

[0, 2, 0, 'DobotSerial', '0.0.0', 31, 0, 0.0]


In [196]:
db.board.read_coords(5)

RadioButtons(options=('0.1 mm', '1 mm', '10 mm'), value='0.1 mm')

Button(description='-X', style=ButtonStyle())

Button(description='+X', style=ButtonStyle())

Button(description='-Y', style=ButtonStyle())

Button(description='+Y', style=ButtonStyle())

Button(description='-Z', style=ButtonStyle())

Button(description='+Z', style=ButtonStyle())

Button(description='record (leave field empty to stop recording)', style=ButtonStyle())

Text(value='', description='coords on board (e.g. "a2")')

In [266]:
t = db.pieces

In [276]:
db.pieces = Pieces(db).copy_from(t)

In [282]:
db.move_piece([4, 4], [7, 0], 'rook')

In [202]:
db.board.optimize()

[[7. 0.]
 [0. 0.]
 [3. 4.]] [[ 168.06251526 -108.17895508]
 [ 167.61117554   89.96081543]
 [ 285.45141602    7.73980856]]


In [14]:
dist(db.temp['dc'][0], db.temp['dc'][-1])/6

28.015946013219935

In [91]:
db.temp

{'bc': ['e8', 'g7', 'd4', 'e2'],
 'dc': [[267.1821594238281, -24.27154541015625],
  [210.69607543945312, 5.0494513511657715],
  [296.0400695800781, 87.86585235595703],
  [269.6284484863281, 145.03778076171875]],
 'j1': [-5.190655708312988,
  1.3728630542755127,
  16.53109359741211,
  28.276569366455078]}

In [23]:
dType.GetEndEffectorParams(api)

[59.70000076293945, 0.0, 0.0]

In [43]:
for i in range(3):
    vec = db.dobot_xy_from_board_xy(db.temp['bc'][i])
    print(vec)
    print(vec*(length(db.temp['dc'][i])/length(vec)))
    print(length(db.temp['dc'][i]) - length(vec))
    print()

[293.00394265 -41.00261997]
[292.9919131  -41.00093657]
-0.012146768922946194

[191.0431116  77.1240676]
[189.79341002  76.61956331]
-1.3476938230176643

[277.61739522 126.08375106]
[278.45726985 126.46519165]
0.9224349886359846



In [15]:
db.calibrate_pos(method=0)

[[-0.99731327 -0.0732546 ]
 [ 0.0732546  -0.99731327]]
[13.70218526  6.29568487]
28.22
0


In [20]:
data['temp'] = {'bc': ['c4', 'h3', 'h7', 'a6', 'b5'],
 'dc': [[259.0032653808594, -46.066925048828125],
  [284.808349609375, 94.43470001220703],
  [177.1175994873047, 97.26470184326172],
  [204.3495330810547, -105.91143798828125],
  [231.33233642578125, -75.40081787109375]],
 'j1': [-10.085293769836426,
  18.344118118286133,
  28.773529052734375,
  -27.397058486938477,
  -18.052940368652344]}

In [42]:
db.move_piece('e2', 'e4', 'pawn')
input()
db.move_piece('e7', 'e5', 'pawn')
input()
db.move_piece('e1', 'e2', 'king')
input()
db.move_piece('e8', 'e7', 'king')

pawn
pawn

pawn
pawn

king
king

king
king


In [38]:
db.move_piece('e8', 'e7', 'king')

king
king


In [47]:
db.temp

{'bc': ['e8', 'g7', 'd4', 'h1'],
 'dc': [[266.4316101074219, -17.031978607177734],
  [212.35418701171875, 9.959300994873047],
  [295.51904296875, 88.67515563964844],
  [187.85848999023438, 170.5806427001953]],
 'j1': [-3.6577281951904297,
  2.6851744651794434,
  16.702701568603516,
  42.24030685424805]}

In [48]:
with open('coords.pickle', 'wb') as f:
    pickle.dump({'temp':db.temp, 'zero_height':db.zero_height, 'heights':db.pieces_heights}, f)

In [46]:
positions = []
while input() != 'q':
    positions.append(dType.GetPose(api))
with open('positions_to_check', 'wb') as f:
    pickle.dump({'coords':positions, 'offset': dType.GetEndEffectorParams(api)}, f)










q
